version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_BD: mydatabase
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://root:rootpassword@localhost:3306/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  mysql_data:
